name: Sync Investors Table

on:
  schedule:
    - cron: "0 12 * * *" # 8:00 AM EST/EDT (12:00 UTC)
    - cron: "0 14 * * *" # 10:00 AM EST/EDT (14:00 UTC)
    - cron: "0 16 * * *" # 12:00 PM EST/EDT (16:00 UTC)
    - cron: "0 18 * * *" # 2:00 PM EST/EDT (18:00 UTC)
    - cron: "0 20 * * *" # 4:00 PM EST/EDT (20:00 UTC)
    - cron: "0 22 * * *" # 6:00 PM EST/EDT (22:00 UTC)
    - cron: "0 0 * * *"  # 8:00 PM EST/EDT (00:00 UTC)
  workflow_dispatch: # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: pip install requests

      # Run the script to fetch data and create CSV
      - name: Run sync script
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: python syncInvestors.py

      # Commit and push the updated CSV file
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/Investors.csv
          git diff --staged --quiet || git commit -m 'Update Investors.csv'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
