name: Update Fundraising Rounds CSV

on:
  schedule:
    - cron: "0 * * * *" # Every hour at minute 0 (e.g., 00:00, 01:00, ..., 23:00 UTC)
  workflow_dispatch: # Manual trigger

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Ensures checkout uses the token

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: python update_csv.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/fundraising_rounds_companies.csv
          git commit -m "Update CSV from Airtable [hourly]" || echo "No changes to commit"
          git push
        continue-on-error: true # Prevents workflow failure if there are no changes to commit
